name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pacman-catalog
        uses: actions/checkout@v4

      - name: Install dylan-tool
        uses: dylan-lang/install-dylan-tool@v3

      - name: Build pacman-catalog-test-suite
        run: |
          DYLAN_CATALOG=. dylan update
          dylan build -a

      - name: Run pacman-catalog-test-suite
        run: |
          DYLAN_CATALOG=. _build/bin/pacman-catalog-test-suite --report surefire --report-file _build/pacman-catalog-tests.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/_build/*-tests.xml'
          detailed_summary: true
          include_passed: true
